- integration-tests/c-example/lib/structures/simple_unions.h
- server/src/Server.cpp
- server/src/Tests.cpp
- server/src/Tests.h
- server/src/environment/EnvironmentPaths.cpp
- server/src/environment/EnvironmentPaths.h
- server/src/printers/NativeMakefilePrinter.cpp
- server/src/printers/NativeMakefilePrinter.h
- server/src/printers/Printer.cpp
- server/src/printers/TestsPrinter.cpp
- server/src/types/Types.cpp
- server/src/types/Types.h
- server/src/types/TypesResolver.cpp
- server/src/utils/PrinterUtils.cpp
- server/src/utils/PrinterUtils.h
- server/src/visitors/VerboseAssertsParamVisitor.cpp
- server/test/framework/Syntax_Tests.cpp
- server/test/suites/run/timeout/pregenerated_tests/main_test.cpp
- server/test/suites/server/simple_unions.h
- server/test/suites/syntax/CMakeLists.txt
- server/test/suites/syntax/inner_unnamed.c
- server/test/suites/syntax/inner_unnamed.h
- server/test/suites/syntax/pointer_parameters.c
- server/test/suites/syntax/simple_unions.h
- server/test/suites/syntax/structs_with_pointers.c
- vscode-plugin/package.json
Add minimal limit of build and test path, compile exec into .o instead of .so, add support of inner unnamed into struct, set pointer to function as not changeable
> Part of fixes for generate tests on sail

- server/src/BordersFinder.cpp
It happens when functions is placed in namespace
> Invalid cast when parent is NamespaceDecl

- server/src/Paths.cpp
- server/src/building/BuildDatabase.cpp
- server/src/building/BuildDatabase.h
- server/src/utils/CollectionUtils.h
- server/test/framework/Server_Tests.cpp
- server/test/framework/main.cpp
- server/test/suites/installed/CMakeLists.txt
- server/test/suites/installed/main.c
I have put an example of such a project in the test suite `server/test/suites/installed`. If we generate a project model for that, we get one of the possible `link_commands.json` from [there](https://github.com/UnitTestBot/UTBotCpp/issues/90). And since it is hard to distinguish those cases as well as to fix the behavior, I propose the following solution. 
Let's look at dependent file. If there is no target for that, then it's most likely installed library in one of install paths. Based on that, we are able to separate installed files within `BuildDatabase`.
Note: tests are generated successfully, but cannot be run at the moment.
> Support projects where targets depend on installed libraries

- server/src/KleeRunner.cpp
These options are time-consuming and unnecessary since we sanitize sources with UBSan.
> Disable unnecessary '--check-div-zero' and '--check-overshift' options for KLEE

- server/src/clang-utils/SourceToHeaderMatchCallback.cpp
> Don't print 'return' for void and no-return functions

- server/src/building/Linker.cpp
- server/test/framework/Server_Tests.cpp
- server/test/suites/installed/CMakeLists.txt
- server/test/suites/installed/lib.c
- server/test/suites/installed/lib.h
- server/test/suites/installed/main.c
The problem happens for such original link command where installed file is placed before output option
```json
"arguments": [
"/utbot_distr/install/bin/clang",
"-fPIC",
"-O3",
"-DNDEBUG",
"-fuse-ld=gold",
"-shared",
"/usr/lib/x86_64-linux-gnu/libz.so",
"../zstd/libzstd.so",
"-o",
"libSZ.so",
"CMakeFiles/SZ.dir/src/ArithmeticCoding.c.o",
...
]
```
Fixes #148
> Move output option to begin and exclude installed files for archive commands when building IR files

- server/src/KleeGenerator.cpp
- server/src/printers/NativeMakefilePrinter.cpp
Initially, I encountered the issues when was not able to compile the wrapper without the following warning.
```
/home/utbot/projects/coreutils/build/utbot/wrapper/gnulib/lib/malloc/dynarray_resize_wrapper.c:9:8: warning: implicit declaration of function 'gl_dynarray_resize' is invalid in C99 [-Wimplicit-function-declaration]
return gl_dynarray_resize(list, size, scratch, element_size);
^
1 warning generated.
```
Then, I took a closer look at compile command for the wrapper and didn't see anything suspicious. So I compared include paths of given command for the wrapper (on the left) and initial command from `cc.json` (on the right).
As it turned out, `#include <dynarray.h>` is looked up [differently](https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html) due to the extra `-I` option. …
> Change '-I' to '-iquote' option for the search of header files in cases where we add current directory to the list to be searched

- server/src/NameDecorator.cpp
- server/src/NameDecorator.h
- server/src/clang-utils/SourceToHeaderMatchCallback.cpp
- server/src/clang-utils/SourceToHeaderRewriter.cpp
- server/test/framework/Server_Tests.cpp
- server/test/suites/stddef/CMakeLists.txt
- server/test/suites/stddef/stddef.c
Fix #167 
- Canonical types are used (`int` for C-like `wchar_t`) in the test source files, so we don't care about them there
- Non-canonical types are redefined (C-like `wchar_t` for `int`) within the scope of the test header file
Example of work for `utbot_tests/gl/lib/mbsalign_test.h`:
> Introduce 'wchar_t' type using '#define' within the scope of test header

- server/src/KleeRunner.cpp
- server/src/commands/Commands.cpp
- server/src/commands/Commands.h
- server/src/utils/CLIUtils.h
- server/src/utils/KleeUtils.cpp
- server/src/utils/KleeUtils.h
Closes #161 
1. Run `utbot server --verbosity debug --klee-process-number 8`
2. Request generation for file
3. Check logs
```
Klee command :: klee ... --process-number=8 ... /home/utbot/tmp/utbot-ZZR7/coreutils/build/lib/libcoreutils.bc --sym-stdin 64
```
> Create command line option '--klee-process-number' whose value is passed to '--process-number' of KLEE (default=5)

- server/src/Paths.cpp
- server/src/Paths.h
- server/src/building/Linker.cpp
- server/src/building/Linker.h
- server/src/coverage/LlvmCoverageTool.cpp
- server/src/printers/DefaultMakefilePrinter.h
- server/src/printers/NativeMakefilePrinter.cpp
- server/src/printers/NativeMakefilePrinter.h
- server/src/printers/TestMakefilesPrinter.cpp
- server/src/printers/TestMakefilesPrinter.h
- server/src/utils/MakefileUtils.cpp
- server/src/utils/MakefileUtils.h
This pr fix [issue-143](https://github.com/UnitTestBot/UTBotCpp/issues/143) create 3 makefile for 1 file:
1) same as before [commit](https://github.com/UnitTestBot/UTBotCpp/commit/e1a96d9cae936a8735998871f3a38f6ad4178e3f#diff-155fa58ace015058333d0b5407eac8d3c65d77a1d9c2132417be735f259064a1R406) with name `__filename_shared.mk`
2) like after this  [commit](https://github.com/UnitTestBot/UTBotCpp/commit/e1a96d9cae936a8735998871f3a38f6ad4178e3f#diff-155fa58ace015058333d0b5407eac8d3c65d77a1d9c2132417be735f259064a1R406)  with name `__filename_obj.mk`.
3) same name as before that has three targets
* `bin` that just call bin of `__filename_shared.mk`
* `run` try call `run` target of `__filename_shared.mk` and if fail call `run` target of `__filename_obj.mk`
* `clean` just run `clean` target …
> Compile tests 2 way by shared lib or object. issue-143

- server/src/printers/NativeMakefilePrinter.cpp
- server/src/visitors/ParametrizedAssertsVisitor.cpp
```cpp
TEST(regression, make_node_op_equals_test_1)
{
struct mode_change * actual = make_node_op_equals(0U, 0U);
attribute ((aligned(1))) struct mode_change expected[1] = {{'=', '\x01', 4095U, 0U, 0U}};
for (int it_2_0 = 0; it_2_0 < 1; it_2_0 ++) {
EXPECT_EQ(expected[it_2_0], actual[it_2_0]);
}
}
```
```cpp
TEST(regression, make_node_op_equals_test_1)
{
struct mode_change * actual = make_node_op_equals(0U, 0U);
struct mode_change expected[1] = {{'=', '\x01', 4095U, 0U, 0U}};
for (int it_2_0 = 0; it_2_0 < 1; it_2_0 ++) {
EXPECT_EQ(expected[it_2_0], actual[it_2_0]);
}
}
```
> Don't print alignment for expected values

- server/src/printers/TestsPrinter.cpp
```cpp
TEST(error, base64_encode_fast_test_3)
{
char in[] = "ccccaccccc";
char out[] = "accccccaca";
base64_encode_fast(in, 2L, out);
char expected_out[] = {'\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0'};
for (int it_6_0 = 0; it_6_0 < 10; it_6_0 ++) {
EXPECT_EQ(expected_out[it_6_0], out[it_6_0]);
}
}
```
```cpp
TEST(error, base64_encode_fast_test_3)
{
char in[] = "cccccacccc";
char out[] = "accbccccca";
base64_encode_fast(in, 2L, out);
}
```
> Don't print asserts for error suite

- server/src/coverage/LlvmCoverageTool.cpp
#173 
- Fix changes the `llvm-cov export` call by extension of parameters set:
adding the tested files as sources to restrict the coverage report JSON output.
In case of `coreutils` it reduces the JSON size from 100M to 2M.
- The command line for `llvm-cov export` was optimized by removing identical
`-object BIN` switches.
Related problem (not fixed): `Paths::testPathToSourcePath` does not work
for `*.cpp` files.
> UTBotCpp-173 [coreutils] Collection of coverage takes too long

- server/src/building/Linker.cpp
- server/src/building/Linker.h
Previously it could be reused between different builds, which is wrong.
> Generate separate output bitcode file when non-root target is chosen

- server/src/Tests.cpp
- server/src/Tests.h
- server/src/printers/TestsPrinter.cpp
- server/src/printers/TestsPrinter.h
- server/src/types/Types.h
- server/src/types/TypesResolver.cpp
- server/src/visitors/AssertsVisitor.cpp
- server/src/visitors/ParametrizedAssertsVisitor.cpp
- server/src/visitors/VerboseAssertsReturnValueVisitor.cpp
- server/src/visitors/VerboseParameterVisitor.cpp
- server/test/framework/Library_Test.cpp
- server/test/framework/Regression_Tests.cpp
- server/test/framework/Server_Tests.cpp
- server/test/framework/Stub_Tests.cpp
- server/test/framework/Syntax_Tests.cpp
- server/test/framework/Targets_Test.cpp
- server/test/framework/TestUtils.cpp
- server/test/framework/TestUtils.h
UTBotCpp-253 Better structure fields initialization in generated tests#253
- implemented multiline printer with generation of field prefixes (~ `.field=`)
- separated the cases: c++ initializer-list of a member in constructor/c-like init lists
(labels like `.field=` are not supported in c++ initializer-list, the comments are used instead)
- test coverage
> UTBotCpp-253 Better structure fields initialization in generated tests #253

- server/src/printers/KleeConstraintsPrinter.cpp
- server/test/framework/Regression_Tests.cpp
- server/test/suites/regression/CMakeLists.txt
- server/test/suites/regression/GH215.c
> Use klee_assume(s[N - 1] == '\0') call for the last element of string

- server/proto/testgen.proto
- server/src/KleeGenerator.cpp
- server/src/Paths.cpp
- server/src/Paths.h
- server/src/building/Linker.cpp
- server/src/coverage/Coverage.cpp
- server/src/coverage/Coverage.h
- server/src/coverage/CoverageAndResultsGenerator.cpp
- server/src/coverage/CoverageTool.cpp
- server/src/coverage/CoverageTool.h
- server/src/coverage/GcovCoverageTool.cpp
- server/src/coverage/GcovCoverageTool.h
- server/src/coverage/LlvmCoverageTool.cpp
- server/src/coverage/LlvmCoverageTool.h
- server/src/coverage/TestRunner.cpp
- server/src/coverage/TestRunner.h
- server/src/printers/CoverageAndResultsStatisticsPrinter.cpp
- server/src/printers/CoverageAndResultsStatisticsPrinter.h
- server/src/streams/coverage/CLICoverageAndResultsWriter.cpp
- server/src/streams/coverage/CLICoverageAndResultsWriter.h
- server/src/streams/coverage/CoverageAndResultsWriter.h
- server/src/streams/coverage/ServerCoverageAndResultsWriter.cpp
- server/src/streams/coverage/ServerCoverageAndResultsWriter.h
- server/src/utils/MakefileUtils.cpp
- server/src/utils/MakefileUtils.h
- server/test/framework/CLI_Tests.cpp
- server/test/framework/Server_Tests.cpp
- server/test/framework/Syntax_Tests.cpp
- server/test/framework/TestUtils.cpp
- server/test/framework/TestUtils.h
After tests execution from CLI user can find coverge and results statistics report in .csv file. The table looks like the following:
|Filename|Google Test Execution Time (s)|Total Tests Number|Passed Tests Number|Failed Tests Number|Death Tests Number|Interrupted Tests Number|Total Lines Number|Covered Lines Number|Line Coverage Ratio (%)|
|--------|------------------------------|------------------|-------------------|-------------------|------------------|------------------------|------------------|--------------------|-----------------------|
|src/simple_calc.c|0                             |2                 |2                  |0                  |0                 |0                       |11                |9                   |81.818182              |
|main.c  |0.004 …
> Add coverage and results statistics report

- .github/workflows/publish-c-family-cli-image.yml
- docker/Dockerfile_c_family_cli
- docker/get_c_family_cli_download_url.py
There were added scripts allowing to publish Java CLI images on GitHub Packages.
Fixes #263
Scripts were tested on fork.
>  Publish C/C++ CLI docker images on GitHub Packages

- server/src/building/UserProjectConfiguration.cpp
- add cmake options:
-DCMAKE_{ASM,C,CPP}_USE_RESPONSE_FILE_FOR_INCLUDES=OFF
-DCMAKE_{ASM,C,CPP}_USE_RESPONSE_FILE_FOR_OBJECTS=OFF
-DCMAKE_{ASM,C,CPP}_USE_RESPONSE_FILE_FOR_LIBRARIES=OFF
> #231 Compile database may content response files

- server/src/building/Linker.cpp
- server/test/framework/Regression_Tests.cpp
- server/test/suites/regression/CMakeLists.txt
- server/test/suites/regression/ISSUE-140/CMakeLists.txt
- server/test/suites/regression/ISSUE-140/module/libfunc.c
- server/test/suites/regression/ISSUE-140/module/libfunc.h
> Fix generate for folder

- server/src/printers/TestsPrinter.cpp
- server/test/framework/CLI_Tests.cpp
- introduced a synthetic order for problems that were found by KLEE
> [BUG] CLI_Test.Generate_Project_Tests fails on some PCs #347

- server/src/KleeRunner.cpp
- server/src/SARIFGenerator.cpp
- server/src/streams/tests/CLITestsWriter.cpp
- server/src/streams/tests/CLITestsWriter.h
- `results` entry in json need to be an empy vector, not `null` if no error
- logging was adjusted for CLI mode
- relative path calculation was extended for the case of CLI run inside the project folder
> [BUG] SARIF report is not recognized by github #352

- .github/workflows/matrix.json
- docker/Dockerfile_base
- server/src/KleeRunner.cpp
- server/src/KleeRunner.h
- server/src/Paths.cpp
- server/src/Paths.h
- server/src/SARIFGenerator.cpp
- server/src/Tests.cpp
- server/src/Tests.h
- server/src/building/BuildDatabase.cpp
- server/src/building/BuildDatabase.h
- server/src/building/Linker.cpp
- server/src/utils/HashUtils.cpp
- fix SARIF genetarion in tests (build dir :==: src dir)
- fix 32bit libs installation: added `gcc-multilib` `g++-multilib`
- fix the order of 32bit libs installation in docker (fixind LLVM compilation)
- add 32bit libs for gcc-9 to support cross-compilation
- for 32bit projects we change KLEE params from defaults:
--allocate-determ-size: 100 -> 1
--allocate-determ-start-address: 0x7ff30000000 -> 0x10000
> #216 UTBotCpp does not support test generation for 32bit projects

- vscode-plugin/src/config/defaultValues.ts
- vscode-plugin/src/explorer/utbotExplorer.ts
- vscode-plugin/src/explorer/utbotExplorerElement.ts
- vscode-plugin/src/utils/pathUtils.ts
[BUG] Bad path entry in `unittestbot.paths.sourceDirectories` parameter on Windows OS #376
- change path -> fsPath when getting root location
> [BUG] Bad path entry in `unittestbot.paths.sourceDirectories` parameter on Windows OS #376

- server/src/utils/JsonUtils.cpp
- parse leading lines as warning with logging those lines
> [BUG] Cannot parse coverage.json as it contains warnings #345

- clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/client/handlers/ProjectConfigurationHandler.kt
- clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/client/handlers/SourceCode.kt
- clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/client/handlers/TestsStreamHandler.kt
- clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/client/requests/test/BaseTestsRequest.kt
- clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/ui/services/TestsResultsStorage.kt
- clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/utils/FileUtils.kt
- clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/utils/PathUtils.kt
- In remote scenario: backup previous sarif report (logic of naming old report was taken from VSCode) 
- fix: added newTestsGenerated method to TestsResultStorage in order to update icons to default when new tests are generated
- removed old code from TestsResultStorage related to listening to vfs events
> backup sarif report

- clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/actions/generate/RunAllTestsWithCoverageAction.kt
- clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/client/handlers/CoverageAndResultsHandler.kt
- clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/client/requests/RunAllTestsWithCoverageRequest.kt
- clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/coverage/Coverage.kt
- clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/coverage/UTBotCoverageRunner.kt
- clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/coverage/UTBotCoverageSuite.kt
- clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/grpc/ActionsGrpcRequests.kt
- clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/ui/targetsToolWindow/UTBotTargetsController.kt
- clion-plugin/src/main/resources/META-INF/plugin.xml
use Map<String, Coverage> to gather coverage similar to vscode
add action for running all tests with coverage in project
> add run all tests and show coverage action

- clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/ui/sourceFoldersView/UTBotProjectViewPaneForSettings.kt
> fix project view pane is not updated after changing directories in settings

- clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/ui/testsResults/UTBotTestRunLineMarkerProvider.kt
closes #394 
To prevent run icons from showing in non-utbot-tests, add a condition to show them only in tests dir and in files which names contain word `test`.
> fix: show run icons only for files in tests directory

- clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/client/Client.kt
- clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/settings/UTBotAllProjectSettings.kt
- clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/ui/ObservableValue.kt
- clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/ui/wizard/UTBotBaseWizardStep.kt
- clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/ui/wizard/UTBotWizard.kt
- clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/ui/wizard/steps/ConnectionStep.kt
- clion-plugin/src/main/resources/media/installation.html
closes #387 
before fix:
after: 
also after unchecking values are restored:
> wizard ui improvements

- server/src/Tests.cpp
- server/src/clang-utils/SourceToHeaderRewriter.cpp
- server/src/printers/TestsPrinter.cpp
- server/src/utils/PrinterUtils.cpp
- server/src/utils/PrinterUtils.h
- server/src/visitors/AssertsVisitor.cpp
- server/test/framework/Syntax_Tests.cpp
- server/test/suites/coverage/pregenerated_tests/dependent_functions_dot_c_test.cpp
- server/test/suites/coverage/pregenerated_tests/simple_class_dot_cpp_test.cpp
- server/test/suites/syntax/floats_special.c
- server/test/suites/syntax/floats_special.h
- use `EXPECT_FLOAT_EQ` and `EXPECT_DOUBLE_EQ` instead of `EXPECT_NEAR`
- remove insertion obsolete `utbot_abs_error` to the code
- support comparison `NAN` and `INFINITY` consts
- make inclusion of `main.c` wrapper with relative path
> [BUG] Unnecessary "utbot_abs_error" constant added to the test #405

- server/src/ReturnTypesFetcher.cpp
- server/src/Server.cpp
- server/src/Synchronizer.cpp
- server/src/fetchers/Fetcher.cpp
- server/src/fetchers/Fetcher.h
- server/src/fetchers/TypeDeclsMatchCallback.cpp
- server/src/stubs/StubGen.cpp
- server/test/framework/Regression_Tests.cpp
- server/test/framework/Syntax_Tests.cpp
- server/test/suites/regression/CMakeLists.txt
- server/test/suites/regression/PR124.c
* unused fetcher field removed
* useless unit test removed
* bit fields tests updated
> fetcher & tests minor fixes

- server/src/types/TypesResolver.cpp
- currently the size is stored in bytes: fix regression from `Support bit field in struct #237`
> Fail run test for function sumSignArray [BUG] #464

- server/src/types/TypesResolver.cpp
- code examples shows, that `returnType->getPointeeType().getBaseTypeIdentifier()` can be null
> [BUG] Segmentation Fault in user project #473

- server/src/building/ProjectBuildDatabse.cpp
- server/src/commands/Commands.h
- server/src/coverage/GcovCoverageTool.cpp
- server/src/coverage/LlvmCoverageTool.cpp
- server/src/coverage/TestRunner.cpp
Ignore read json error
Set default timeout for run tests 30
> Fix generation for coreutils

- server/src/Server.cpp
- server/src/Synchronizer.cpp
- server/src/Synchronizer.h
closes #517 
The problem was in stubs synchronization. When server synced stubs it deleted all files that are not in current target in function `prepareDirectory()`, though those stubs could be needed later
> [BUG] No tests generated for function calling function from another module #517

- server/src/printers/TestsPrinter.cpp
- server/src/printers/TestsPrinter.h
- server/test/framework/Syntax_Tests.cpp
Add FAIL() assertion to generated tests in no verbose mode. The line with FAIL() assertion is unreachable in some tests but it gives additional information to the user to make the tests easier to read.
I add a unit test to check that the code of generated tests (error suit) has the line with FAIL() assertion. I decided not to use statuses from the tests execution because the line with FAIL() assertion can be unreachable.
Refs: #472
> TestsPrinters.cpp: add FAIL() assertion to error tests.

- server/src/Tests.cpp
- server/test/framework/Regression_Tests.cpp
- server/test/framework/Syntax_Tests.cpp
Fixed Incorrect check post condition of char* ([BUG] #463) from string to array
> Change representation of char* from string to array

- vscode-plugin/src/config/notificationMessages.ts
Add links in "SARIF and SFTP not install" warnings in vscode plugin. Now it looks like " Please, **install** MS Sarif Viewer" and install is clickable.  Bug #461
> Fix unclickable SFTP and SARIF links in vscode plugin warnings (Bug #461)

- server/src/Synchronizer.cpp
- server/src/Synchronizer.h
Added a separate check for wrappers.
> Refresh wrappers after modifying source files.

- server/src/Tests.cpp
- server/src/Tests.h
- server/src/coverage/TestRunner.cpp
- server/src/fetchers/GlobalVariableUsageMatchCallback.cpp
- server/src/printers/KleePrinter.cpp
- server/src/printers/Printer.cpp
- server/src/printers/Printer.h
- server/src/printers/TestsPrinter.cpp
- server/src/utils/CollectionUtils.h
- server/test/framework/Regression_Tests.cpp
- server/test/framework/Server_Tests.cpp
- server/test/suites/regression/CMakeLists.txt
- server/test/suites/regression/issue-514.c
Closes #514 
To fix the problem extern variable declaration was added to KLEE wrapper and gtest file.
> External variables support (closes #514)

- README.md
Update UTBot online demo link in the README to https://www.utbot.org/demo/?language=C. 
Previous link (https://www.utbot.org/utbot) returns 404.
> Update UTBot online demo link in the README

- server/src/Tests.h
- server/src/printers/Printer.cpp
- server/src/printers/Printer.h
- server/src/printers/TestsPrinter.cpp
- server/src/types/Types.cpp
- server/src/types/Types.h
- server/test/framework/Syntax_Tests.cpp
- server/test/suites/syntax/CMakeLists.txt
- server/test/suites/syntax/function_with_rvalue_params.cpp
- server/test/suites/syntax/function_with_rvalue_params.h
Simple change that use `std::move` for rvalue parameters
close #64
> Add rvalue support

- .github/workflows/build-utbot.yml
- server/src/building/TargetBuildDatabase.cpp
- server/src/building/TargetBuildDatabase.h
- server/src/testgens/FileTestGen.cpp
- server/src/testgens/LineTestGen.cpp
- server/src/testgens/ProjectTestGen.cpp
- server/src/testgens/ProjectTestGen.h
- server/test/framework/Server_Tests.cpp
- server/test/framework/Stub_Tests.cpp
- server/test/framework/Syntax_Tests.cpp
When test are generating for file, function, line, assertion, class or predicate and automatic target is chosen, UTBot selects target that contains the source file
> Fix target selection for files and lines (closes #557)

- .github/workflows/build-utbot.yml
- .github/workflows/publish-utbot.yml
- server/src/Paths.cpp
- server/src/Paths.h
- server/src/building/BuildDatabase.cpp
- server/src/building/ProjectBuildDatabse.cpp
- server/src/clang-utils/SourceToHeaderMatchCallback.cpp
- server/src/clang-utils/SourceToHeaderMatchCallback.h
- server/src/fetchers/FunctionDeclsMatchCallback.cpp
This PR fixes several problems that appeared on the project scalapack:
1) Avoid .f and .f.o files as source files.
2) Use definition parameters (cause due to "extern func();" declaration function`s parameters were lost)
3) Fix wrong test header and wrapper printing due to old style function definition.
> Changes for using UTBotCPP on scalapack project.

- server/proto/testgen.proto
- server/src/ProjectContext.cpp
- server/src/ProjectContext.h
- server/src/Synchronizer.cpp
- server/src/building/CompileCommand.cpp
- server/src/building/ProjectBuildDatabse.cpp
- server/src/coverage/TestRunner.cpp
- server/src/utils/CompilationUtils.cpp
- server/src/utils/StringUtils.cpp
- server/src/visitors/ParametrizedAssertsVisitor.cpp
- server/test/framework/BaseTest.h
- server/test/framework/Server_Tests.cpp
- server/test/framework/Stub_Tests.cpp
- vscode-plugin/src/client/client.ts
- vscode-plugin/src/requests/protos.ts
1) Changes in ProjectBuildDatabse.cpp - search in the map by absolute and relative paths.
2) Changes in CompilationUtils.cpp - due to incorrect transfer of directory name in compile_command.json
> Changes to launch a UTBot on open source projects (libbpf and curl)

- server/src/commands/Commands.h
The type loguru::NamedVerbosity is int in fact,so it has no initialized value when it is defined.It has dirty data where it is in the line 88 in CLIUtils.cpp.This dirty data can cause the log info cannot send to the client sometimes.
> fix the bug log cannot send to client sometimes
