UnitTestBot/UTBotCpp

- .github/workflows/publish-utbot.yml
- integration-tests/installation_checks/automated_install_checks.sh
- integration-tests/installation_checks/clean.sh
Automation check on the installation script runs a server process
> Automated Checks for Installation Script

- server/src/building/BuildDatabase.cpp
- server/src/building/CompileCommand.cpp
- server/src/building/CompileCommand.h
- server/test/suites/datacom/CMakeLists.txt
> Remove -Werror flag or option from BuildDatabase

- server/src/fetchers/FetcherUtils.cpp
- server/src/fetchers/FetcherUtils.h
- server/src/tasks/BaseForkTask.h
- server/src/tasks/ShellExecTask.h
- server/src/utils/CompilationUtils.cpp
- server/src/utils/CompilationUtils.h
- server/src/utils/ExecUtils.h
- server/src/utils/ExecutionResult.h
- server/test/framework/Server_Tests.cpp
- server/test/framework/main.cpp
- server/test/suites/stddef/CMakeLists.txt
- server/test/suites/stddef/stddef.c
> Set '--resource-dir' option for Clang tool

- server/src/printers/KleeConstraintsPrinter.cpp
- server/src/printers/Printer.cpp
- server/src/printers/Printer.h
- server/src/visitors/KleeAssumeParamVisitor.cpp
- server/src/visitors/KleeAssumeReturnValueVisitor.cpp
- server/src/visitors/ParametrizedAssertsVisitor.cpp
- server/src/visitors/VerboseAssertsVisitor.cpp
- server/test/framework/Regression_Tests.cpp
- server/test/suites/regression/CMakeLists.txt
- server/test/suites/regression/PR120.c
> Make unique loop variables globally

- server/src/types/TypesResolver.cpp
- server/test/framework/Regression_Tests.cpp
- server/test/suites/regression/CMakeLists.txt
- server/test/suites/regression/PR124.c
> Skip unnamed bit fields

- integration-tests/c-example/lib/linked-list/linked-list.c
- integration-tests/c-example/lib/linked-list/linked-list.h
- integration-tests/c-example/lib/stubs/stubs.c
- integration-tests/c-example/lib/stubs/stubs.h
- server/src/KleeRunner.cpp
- server/src/KleeRunner.h
- server/src/Server.cpp
- server/src/Tests.cpp
- server/src/tasks/BaseForkTask.cpp
- server/src/tasks/BaseForkTask.h
- server/test/framework/Syntax_Tests.cpp
- server/test/suites/syntax/CMakeLists.txt
- server/test/suites/syntax/linked_list.c
- server/test/suites/syntax/linked_list.h
- server/test/suites/syntax/stubs.c
- server/test/suites/syntax/stubs.h
Now interactive mode doesn't work on generation tests for project or folder, but for file all are fine. For file `linked-list.cpp` generation time equals 52s for 1 parallel process, 36s - for 5 and 20s - for 10. For other files it's impossible to see difference because number of functions in files are small
> Add interactive mode

- server/src/clang-utils/SourceToHeaderMatchCallback.cpp
> Print typedef for 'wchar_t' in stub headers

- server/src/printers/KleePrinter.cpp
> Replace '#include <stdlib.h>' with declaration of 'calloc' function in klee file

- server/CMakeLists.txt
- server/src/Tests.cpp
- server/src/Tests.h
- server/src/printers/Printer.cpp
- server/src/printers/Printer.h
- server/src/printers/TestsPrinter.cpp
- server/test/framework/Regression_Tests.cpp
- server/test/suites/regression/CMakeLists.txt
- server/test/suites/regression/PR153.c
> Generate stubs for parameters in case of zero regression tests

- server/src/printers/TestsPrinter.cpp
> Insert missing argument for alignment

- server/src/printers/Printer.cpp
> Don't print extra newlines

- server/src/Server.cpp
Reduce time for this type of request
> Turn off all options but TYPE and FUNCTION for ProcessProjectStubsRequest

- server/src/coverage/CoverageAndResultsGenerator.cpp
- server/src/coverage/TestRunner.cpp
- server/src/coverage/TestRunner.h
- server/src/printers/TestMakefilesPrinter.cpp
- server/src/visitors/AssertsVisitor.cpp
- server/test/framework/Server_Tests.cpp
- server/test/framework/Syntax_Tests.cpp
> Add compile check after generate tests into, syntax unit tests.

- server/src/SARIFGenerator.cpp
- server/src/streams/tests/ServerTestsWriter.cpp
- vscode-plugin/package.json
- vscode-plugin/src/responses/responseHandler.ts
- vscode-plugin/src/visualizers/testResultsVisualizer.ts
- fogging unification for local/remote scenario
- global refactoring with renaming
- remmove wrong plugin dependences
> [BUG] SARIF report is not generated for server on local host #340

- vscode-plugin/src/responses/responseHandler.ts
- refresh was implemented as close-open action
> [BUG] SARIF report is not refreshed after new test generation. #364

- .github/workflows/build-utbot.yml
- .github/workflows/publish-utbot.yml
- clion-plugin/build.gradle.kts
- clion-plugin/gradle.properties
- clion-plugin/src/main/resources/META-INF/plugin.xml
- docker/action-scripts/build-clion-plugin.sh
- docker/action-scripts/prepare-ubuntu-release.sh
- docker/action-scripts/runClionIntegrationTests.sh
I tested it in my fork in this pr: https://github.com/vol0n/UTBotCpp/pull/4
actions run: https://github.com/vol0n/UTBotCpp/actions/runs/2815892589
> add plugin artifact during publish-utbot workflow

- .github/workflows/build-utbot.yml
- .github/workflows/publish-base-env.yml
- .github/workflows/publish-c-family-cli-image.yml
- .github/workflows/publish-utbot.yml
Switch to ubuntu-latest, because github deprecate ubuntu 18.04 runners
> Switch to ubuntu-latest

- .github/workflows/matrix.json
- docker/Dockerfile_base
> support grpc 1.49.1

- server/src/Paths.cpp
We need delete this error because it finds problem in KLEE, not in user code
> Delete model and user from error list

- server/src/printers/NativeMakefilePrinter.cpp
Bug [#408](https://github.com/UnitTestBot/UTBotCpp/issues/408)
> Add source file in UTBot test`s Makefiles dependencies

- server/src/building/BuildDatabase.cpp
Add exception due to server fail cause of sigfault.
> Fix server fall.

- server/src/building/BuildDatabase.cpp
- server/src/building/UserProjectConfiguration.cpp
Fix ObjectFileInfo comparator
Add always-make to run bear command
> Fix collection compile info
